server:
  port: 8899
  servlet:
    context-path: /quick

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm
    username: root
    password: 123456

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    view:
      prefix: /
      suffix: .jsp

  thymeleaf:
    cache: false

#mybatis:
#  type-aliases-package: com.crazycode.pojo
#  mapper-locations: classpath:com/crazycode/mapper/*.xml
#  config-location: classpath:mybatis-config.xml

mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: crazycode/mapper/*.xml
  type-aliases-package: com.crazycode.entity

pagehelper:
  reasonable: true
  support-methods-arguments: true